import type { Metadata } from "next";
import "./globals.css";
import { Chakra_Petch } from "next/font/google";
import Navbar from "@/components/Navbar";
const inter = Chakra_Petch({ subsets: ["latin"], weight: ["300"] });

export const metadata: Metadata = {
  title: "Sistema de Control ingresos y egresos de activos",
  description: "Generated by nextJS"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Navbar />
        <main className="mt-20 flex justify-center">{children}</main>
      </body>
    </html>
  );
}
