import type { Metadata } from "next";
import "./globals.css";
import { Chakra_Petch } from "next/font/google";
import { Sidebar } from "@/components/SideBar";
import { MainBar } from "@/components/MainBar";
const inter = Chakra_Petch({ subsets: ["latin"], weight: ["300"] });

export const metadata: Metadata = {
  title: "Sistema de Control ingresos y egresos de activos",
  description: "Generated by nextJS"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="">
          <Sidebar />
          <MainBar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
